[project]
name = "proekt"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4"
dependencies = [
    "django (>=6.0.3,<7.0.0)",
    "pillow (>=12.1.1,<13.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "djangorestframework (>=3.17.1,<4.0.0)",
    "asgiref (==3.11.1)",
    "django-modeltranslation (>=0.20.2,<0.21.0)",
    "django-phonenumber-field (>=8.4.0,<9.0.0)",
    "djangorestframework-simplejwt (>=5.5.1,<6.0.0)",
    "drf-yasg (>=1.21.15,<2.0.0)",
    "django-jazzmin (>=3.0.4,<4.0.0)",
    "django-filter (>=25.2,<26.0)",
    "psycopg2-binary (>=2.9.11,<3.0.0)",
    "djangorestframework-stubs (>=3.16.8,<4.0.0)",
    "phonenumbers (>=9.0.26,<10.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
